name: sync-releases-biblequiz
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag'
        required: true
        type: string
  release:
    types: [prereleased, released, deleted, unpublished]
jobs:
  sync-release:
    uses: biblequiz/BibleQuiz.com/.github/workflows/sync-release-template.yml@main
    with:
      product_name: CoachApp
      commit_changes: true
      tag_name: ${{ inputs.tag_name || github.event.release.tag_name }}
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
