name: sync-releases-biblequiz
on:
  workflow_dispatch:
  release:
    types: [prereleased, released, deleted, unpublished]
jobs:
  sync-release:
    uses: biblequiz/ModernApps/.github/workflows/sync-release-template.yml@master
    with:
      product_name: CoachApp
      commit_changes: false
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
